### PR TITLE
Add default introductory code example

### PR DESCRIPTION
**Pull request by kytrinyx**
Instead of having logic for a fallback in the backend, we're choosing a
default for the snippet file.

For tracks that have core exercises, we pick the first core exercise.
For tracks without these, we pick the first exercise listed in the config.

Note that we're aiming for 10 lines and a max-width of 40 columns.
This solution has a max-width of 63, so we may want to adjust it.

See https://github.com/exercism/meta/issues/89

### CODE REVIEW

**Comment by kytrinyx** [comment]
I think we need to fix this so it doesn't have the conditional in it. That would bring the column count in to where we want it.

**Comment by mfdj** [comment]
Came here from https://twitter.com/kytrinyx/status/903740618559639554

I'm rusty, but used coffeescript regularly for about a year. 

Not sure what the goal is? I followed https://github.com/exercism/meta/issues/89 and noticed a lot of the examples referenced don't accept arguments (they just print hello world?). Is that the ask?

**Comment by paulstraw** [comment]
@kytrinyx I believe this should be set in my commit above, but that might not be the solve you were looking for (not sure if using a param default value is okay for these examples). Happy to amend or let someone else handle if that doesn't work for you. 🙂

**Comment by kytrinyx** [comment]
@paulstraw sorry—I completely forgot to point back to the goal here!

The goal is to have a nice little snippet to introduce the language on https://v2.exercism.io/tracks/coffeescript

They can totally print arguments... if it fits within the 40 character width. We're not too worried about the details, we just want to give a little bit of a taste of what the language looks like on the main page for the language track on the new Exercism site.

**Comment by kytrinyx** [comment]
@paulstraw Oh, also—your example looks great. Want to submit a PR to this repository? I have merge powers (just no CoffeeScript skills).

**Comment by kytrinyx** [comment]
Alrighty. We're set here. Thank you for jumping in, @paulstraw

**Pull request merged**
