### PR TITLE
fix pangram.spec.coffee

### PR DESCRIPTION
**Pull request by ladokp**
@BNAndras, @ErikSchierboom: Since the tests are preventing a submition via online editor, this is a shot in the blue since this strings are the only odd thing I can find in this file.

See: https://github.com/exercism/coffeescript/pull/269#issuecomment-1945922487

### CODE REVIEW

**Comment by ladokp** [comment]
Yes, it's really strange. But this is the only oddity I found in the file. I'm just curious if the tests are successful when doing this "fix"...

**Comment by ladokp** [comment]
I've seen this before: https://github.com/exercism/coffeescript/pull/259#issuecomment-1919050387
Succesfull merge and CI checks but no possibility to submit.

**Comment by BNAndras** [comment]
The CI runs `npm install -g jasmine-node coffeescript` before testing exercises. The test runner has pinned dependencies at https://github.com/exercism/coffeescript-test-runner/blob/main/package-lock.json. That might mean there's a versioning issue here. 

I'd say we update the CI to use the test runner image to test the exercises. That should nip the issue in the bud.

**Comment by ladokp** [comment]
Sounds good. 😀

**Comment by ladokp** [comment]
Would be great if the CI and the test runner are working the same way.

**Comment by ladokp** [comment]
@BNAndras, I looked at the two mentioned packages. The current versions are exactly that ones the test runner is pinned to. Therefore I think that the CI should currently also install exactly this versions when nothing is pinned.

**Comment by ladokp** [comment]
@ErikSchierboom: May we test if my (maybe nonsense) string change makes a difference?

**Comment by ErikSchierboom** [comment]
It _does_ fix the issue. The problem is _not_ the actual test output, which is fine even in the old situation:

```json
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
<testsuite name="Pangram" errors="0" tests="10" failures="0" time="0.004" timestamp="2024-02-16T08:43:18">
  <testcase classname="Pangram" name="empty sentence" time="0.002"></testcase>
  <testcase classname="Pangram" name="perfect lower case" time="0"></testcase>
  <testcase classname="Pangram" name="only lower case" time="0"></testcase>
  <testcase classname="Pangram" name="missing the letter &amp;quot;x&amp;quot;" time="0"></testcase>
  <testcase classname="Pangram" name="missing the letter &amp;quot;h&amp;quot;" time="0"></testcase>
  <testcase classname="Pangram" name="with underscores" time="0.001"></testcase>
  <testcase classname="Pangram" name="with numbers" time="0"></testcase>
  <testcase classname="Pangram" name="missing letters replaced by numbers" time="0"></testcase>
  <testcase classname="Pangram" name="mixed case and punctuation" time="0"></testcase>
  <testcase classname="Pangram" name="a-m and A-M are 26 different characters but not a pangram" time="0"></testcase>
</testsuite>
</testsuites>
```

I think it likely has to do with using the `ast.json` file to extract the test code. Worth fixing in the test runner if would say.

p.s. I can't re-open this PR as it was force pushed or recreated,

**Comment by ladokp** [comment]
Oh, I rebased my branch. Will create a new PR, sorry.

**Comment by ladokp** [comment]
@ErikSchierboom: created #275

**Pull request closed without merging**
