### PR TITLE
Update grains test suite

### PR DESCRIPTION
**Pull request by BNAndras**
@ErikSchierboom, @ladokp noticed an issue where I updated the stub from your code review  but not the CI example. If I had, the CI wouldn't have passed.  I also removed the unused argument on the last test, a copy and paste error.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
Whoops. Sorry

**Comment by ladokp** [comment]
This should fix the error in my opinion. Also the other new exercises are facing the same issue. I have commented in the corresponding pull requests.

**Comment by ladokp** [comment]
I've created PR #250 to fix the test suite. Will also fix the other exercises.

**Comment by ladokp** [comment]
PR #251, #252, #253 were added.

**Pull request merged**
