### PR TITLE
fix protein-translation tests

### PR DESCRIPTION
**Pull request by ladokp**
After failing the test like commented here #259 this is the only oddity I found in the tests.
Can this be the solution to submit the exercise?

### CODE REVIEW

**Comment by ladokp** [comment]
Okay, the pipeline failed. This is not the solution. :-(

**Comment by ladokp** [comment]
rewrote the last test to check for an exception and not a string like seen in other exercise tests. Hope this will solve the issue on submitting the exercise.

**Comment by ladokp** [comment]
Github did not pull my latest commit when PR is closed I assume.

**Comment by ladokp** [comment]
created new PR with current code: #266

**Comment by BNAndras** [comment]
That snippet was modified from queen-attack so you may want to check that test suite too.

**Comment by ladokp** [comment]
Okay, I'll check that too.

**Comment by BNAndras** [comment]
I must have misunderstood the examples for `toThrow` on https://jasmine.github.io/api/edge/matchers.html where it looks like we're passing in the expected error message. Perhaps `toThrowError`  beneath it would be better. We can just specify the expected message.

**Comment by ladokp** [comment]
I hope my fix in #266 should work. It's also based on another exercise's test.

**Comment by ladokp** [comment]
The queen-attack tests are still successful. 🤔 So no error there.

**Pull request closed without merging**
