### PR TITLE
Coffeescript : Queen Attack - Import and class name were broken

### PR DESCRIPTION
**Pull request by oVerde**
Before the fix:
image

After the quick commit:
image

Fully fixed:
image

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
Thanks for the PR. There is indeed a disconnect between the stub that you start with and the tests. I'd prefer the stub to be renamed instead of the tests, as changing the tests will break existing solutions, which we want to prevent. Could you change https://github.com/exercism/coffeescript/blob/main/exercises/practice/queen-attack/queen-attack.coffee to have it define a `Queens` class?

**Comment by oVerde** [comment]
Hi @ErikSchierboom thanks for the response.

The test, as it is now, has mixed expectations for the export name, `Queens` and `QueenAttack`, breaking every submitted code for everyone, my fix aligns to most user submitted solutions, as they follow the stub, since they can't change the spec.

**Review by ErikSchierboom — COMMENTED** [review]
> The test, as it is now, has mixed expectations for the export name, Queens and QueenAttack, breaking every submitted code for everyone

This is quite an odd situtation, I agree.

> my fix aligns to most user submitted solutions, as they follow the stub, since they can't change the spec.

Is that so? If I look at https://exercism.org/tracks/coffeescript/exercises/queen-attack/solutions?not_passed_head_tests=true&page=1 I see most people using `Queens`, not `QueenAttack`.

So while I think most people used `Queens`, I'm fine with changing it to `QueenAttack` as that does make more sense and everything is broken anyway.

One thing that should also be updated accordingly is the example implementation: https://github.com/exercism/coffeescript/blob/main/exercises/practice/queen-attack/.meta/example.coffee

**Comment by oVerde** [comment]
Done @ErikSchierboom :smiley: 

Is anywhere else?

**Comment by ErikSchierboom** [comment]
@oVerde Nope, this is good! Thanks 🎉

**Pull request merged**
